insert into espectadores (ue_nickname, ue_nombre, ue_apellido, ue_correo, ue_fechaNacimiento) values 
('Keylex', 'Jeanine', 'Tunsley', 'jtunsley0@chron.com', '2022-02-14'), 
('Sub-Ex', 'Hillary', 'Johnsey', 'hjohnsey1@mozilla.org', '2022-04-15'), 
('Pannier', 'Maury', 'Byllam', 'mbyllam2@opensource.org', '2022-08-30'), 
('Stim', 'Mellicent', 'Palek', 'mpalek3@jigsy.com', '2022-07-02'), 
('Hatity', 'Shurwood', 'Burbidge', 'sburbidge4@wufoo.com', '2021-12-02'), 
('Hatity', 'Erick', 'Mival', 'emival5@vinaora.com', '2022-05-09'), 
('Stronghold', 'Vi', 'Chevers', 'vchevers6@altervista.org', '2021-10-26'), 
('Zamit', 'Fancie', 'O''Criane', 'focriane7@cornell.edu', '2022-01-03'), 
('Wrapsafe', 'Benn', 'Reinbach', 'breinbach8@apache.org', '2022-05-29'), 
('Lotlux', 'Elicia', 'Koppen', 'ekoppen9@bizjournals.com', '2021-09-11'), 
('Voyatouch', 'Lexi', 'Orrum', 'lorruma@ask.com', '2022-05-23'), 
('Tampflex', 'My', 'Oboy', 'moboyb@google.com.hk', '2022-01-26'), 
('Job', 'Inger', 'Dono', 'idonoc@seesaa.net', '2022-01-13'), 
('Konklab', 'Lizette', 'Steers', 'lsteersd@printfriendly.com', '2022-01-22'), 
('Domainer', 'Brade', 'Kohnemann', 'bkohnemanne@apple.com', '2022-06-06'), 
('Y-find', 'Dieter', 'Camacho', 'dcamachof@globo.com', '2021-10-25'), 
('Rank', 'Imojean', 'Styles', 'istylesg@aboutads.info', '2022-06-11'), 
('Greenlam', 'Graham', 'Ghelardoni', 'gghelardonih@hhs.gov', '2022-02-20'), 
('Cookley', 'Henrie', 'Minchinton', 'hminchintoni@dyndns.org', '2022-04-09'), 
('Span', 'Lola', 'Montez', 'lmontezj@vkontakte.ru', '2022-03-05');


insert into artistas (ua_nickname, ua_nombre, ua_apellido, ua_correo, ua_fechaNacimiento, ua_descripcion, ua_biografia, ua_sitioWeb) values 
('Regrant', 'Clementius', 'Gaskal', 'cgaskal0@usa.gov', '2022-01-20', 'Jabbercube', 'Quality Control Specialist', 'marketwatch.com'),
('Kanlam', 'Madelene', 'Grisley', 'mgrisley1@gnu.org', '2022-02-25', 'Twimbo', 'Food Chemist', 'census.gov'),
('Treeflex', 'Birdie', 'Tankus', 'btankus2@netlog.com', '2022-07-25', 'Zoovu', 'VP Product Management', 'ycombinator.com'),
('Span', 'Ingaborg', 'Exell', 'iexell3@fastcompany.com', '2022-05-07', 'Aimbo', 'Statistician III', 'pagesperso-orange.fr'),
('Rank', 'Golda', 'Burgan', 'gburgan4@wikia.com', '2022-03-21', 'Browseblab', 'Sales Associate', 'rambler.ru'),
('Otcom', 'Kimmi', 'Florez', 'kflorez5@vkontakte.ru', '2022-06-04', 'Twinder', 'General Manager', 'paypal.com'),
('Transcof', 'Berna', 'Newcome', 'bnewcome6@altervista.org', '2022-06-16', 'Wordify', 'Senior Sales Associate', 'creativecommons.org'),
('Home Ing', 'Ferrell', 'Pabst', 'fpabst7@dmoz.org', '2022-02-06', 'Quatz', 'Payment Adjustment Coordinator', 'google.it'),
('Domainer', 'Luciana', 'Hegarty', 'lhegarty8@soup.io', '2022-06-02', 'Jatri', 'Biostatistician I', 'virginia.edu'),
('Greenlam', 'Zorah', 'Woodall', 'zwoodall9@bing.com', '2021-11-12', 'Fivebridge', 'Nurse Practicioner', 'bbc.co.uk'),
('Opela', 'Konstanze', 'D''Alesco', 'kdalescoa@infoseek.co.jp', '2022-05-29', 'Youspan', 'Media Manager II', 'apple.com'),
('Transcof', 'Britney', 'Reavell', 'breavellb@slideshare.net', '2021-10-16', 'Zoonder', 'Research Assistant IV', 'diigo.com'),
('Mat Lam Tam', 'Selene', 'Smith', 'ssmithc@jalbum.net', '2022-03-30', 'Camimbo', 'Financial Analyst', 'marketwatch.com'),
('Tresom', 'Mamie', 'Burling', 'mburlingd@multiply.com', '2021-10-18', 'Tagpad', 'Chief Design Engineer', 'alexa.com'),
('Veribet', 'Cherida', 'Hover', 'chovere@i2i.jp', '2021-10-26', 'Flipstorm', 'Automation Specialist II', 'bing.com'),
('Ronstring', 'Godard', 'Rushworth', 'grushworthf@elpais.com', '2022-07-07', 'Kwilith', 'Associate Professor', 'purevolume.com'),
('Duobam', 'Fanya', 'Schuelcke', 'fschuelckeg@ox.ac.uk', '2021-10-29', 'Twitterbeat', 'Budget/Accounting Analyst III', 'arstechnica.com'),
('Matsoft', 'Marty', 'Treasaden', 'mtreasadenh@theglobeandmail.com', '2021-10-12', 'Trilia', 'Office Assistant II', 'reddit.com'),
('Fixflex', 'Savina', 'Russo', 'srussoi@skype.com', '2022-08-03', 'Skibox', 'VP Product Management', 'canalblog.com'),
('Matsoft', 'Cassandra', 'Lamlin', 'clamlinj@shareasale.com', '2021-11-22', 'Camimbo', 'Developer III', 'vkontakte.ru');

insert into plataformas (pl_nombre, pl_descripcion, pl_url) values 
('Meta', 'Conglomerado estadounidense de tecnología y redes sociales', 'www.facebook.com'),
('Youtube', 'Sitio web para subir videos y compartirlos con todo el mundo', 'www.youtube.com'),
('Twitch', 'Plataforma perteneciente a la empresa Amazon que permite realizar transmisiones en vivo', 'www.twitch.tv'),
('Nebula', 'Proveedor global independiente de servicios de transmisión de video a pedido', 'nebula.app');