INSERT INTO `espectaculos_paquetes` (`es_paq_nombrePaquete`, `es_paq_nombreEspectaculo`, `es_paq_plataformaAsociada`) VALUES
('Nice and spicy', 'Ante todo calamidades de la vida', 'Twitch'),
('sixPack', 'Ante todo calamidades de la vida', 'Twitch'),
('Nice and spicy', 'El arte de dormir con los ojos abiertos', 'Nebula'),
('sixPack', 'El arte de dormir con los ojos abiertos', 'Nebula'),
('Las aventuras de ayer y hoy', 'El espectaculo de britney lanza', 'Meta'),
('sixPack', 'El espectaculo de britney lanza', 'Meta'),
('Las aventuras de ayer y hoy', 'God of games', 'Nebula'),
('sixPack', 'God of games', 'Nebula'),
('Nice and spicy', 'La boda de tu tia', 'Twitch'),
('sixPack', 'La boda de tu tia', 'Twitch'),
('Las aventuras de ayer y hoy', 'La Ópera Metropolitana de Nueva York', 'Meta'),
('sixPack', 'La Ópera Metropolitana de Nueva York', 'Meta'),
('Nice and spicy', 'Luciana decora tu pelo', 'Youtube'),
('sixPack', 'Luciana decora tu pelo', 'Youtube'),
('sixPack', 'Save or not to save', 'Meta'),
('Paquete de Bandas', 'Los Village Volvieron', 'Instagram Live'),
('Paquete de Bandas', 'Global Spirit', 'Facebook Watch'),
('Paquete Solistas', 'Memphis Blues World', 'Twitter Live'),
('Paquete Solistas', 'Springsteen on Broadway', 'Youtube'),
('Paquete Latino', 'Bien de Familia', 'Twitter Live'),
('Paquete Latino', '30 años', 'Twitter Live');