INSERT INTO `espectaculos_paquetes` (`es_paq_nombrePaquete`, `es_paq_nombreEspectaculo`, `es_paq_plataformaAsociada`) VALUES
('Nice and spicy', 'Ante todo calamidades de la vida', 'Twitch'),
('sixPack', 'Ante todo calamidades de la vida', 'Twitch'),
('Nice and spicy', 'El arte de dormir con los ojos abiertos', 'Nebula'),
('sixPack', 'El arte de dormir con los ojos abiertos', 'Nebula'),
('Las aventuras de ayer y hoy', 'El espectaculo de britney lanza', 'Meta'),
('sixPack', 'El espectaculo de britney lanza', 'Meta'),
('Las aventuras de ayer y hoy', 'God of games', 'Nebula'),
('sixPack', 'God of games', 'Nebula'),
('Nice and spicy', 'La boda de tu tia', 'Meta'),
('sixPack', 'La boda de tu tia', 'Twitch'),
('Las aventuras de ayer y hoy', 'La Ópera Metropolitana de Nueva York', 'Meta'),
('sixPack', 'La Ópera Metropolitana de Nueva York', 'Meta'),
('Nice and spicy', 'Luciana decora tu pelo', 'Youtube'),
('sixPack', 'Luciana decora tu pelo', 'Youtube'),
('sixPack', 'Save or not to save', 'Meta');